env:
  browser: true
  es6: true

extends:
  - "plugin:react/recommended"
  - "airbnb"

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: "module"

plugins:
  - "react"
  - "simple-import-sort"
  - "sort-destructure-keys"

rules:
  "no-multiple-empty-lines": ["error", { "max": 1 }]
  "simple-import-sort/sort": 2
  "react/jsx-sort-props": 2
  "react/prop-types": 0
  "sort-destructure-keys/sort-destructure-keys": 2
